name: Terraform Apply

on:
  workflow_dispatch:
    inputs:
      branch:
        type: choice
        description: "Branch name to checkout"
        required: true
        default: "main"
        options:
          - main
          - feature1
      environment:
        type: choice
        description: "Environment name"
        required: true
        default: "dev"
        options:
          - dev
          - prd
          - pre

permissions:
  id-token: write
  contents: read         

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/environments/dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      - name: Terraform Init
        run: terraform init
      - name: Terraform Apply
        run: terraform apply -auto-approve
